# Generated by Django 5.0 on 2024-01-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
                ('course_info', models.TextField()),
                ('start_date', models.DateField()),
                ('course_duration', models.IntegerField()),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('teachers', models.ManyToManyField(related_name='courses', to='teachers.teacher')),
            ],
        ),
    ]
