# Generated by Django 5.0 on 2024-01-09 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(max_length=300)),
                ('teacherPhoto', models.ImageField(upload_to='teacher_photos/')),
                ('jobTitle', models.CharField(default='', max_length=100)),
                ('teacherRating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('numStudents', models.PositiveIntegerField()),
                ('numCourses', models.PositiveIntegerField()),
                ('teacherInfo', models.TextField()),
                ('facebookUrl', models.URLField()),
                ('instagramUrl', models.URLField()),
                ('linkedinUrl', models.URLField()),
            ],
        ),
    ]
